#!/usr/bin/bash

function start_one() {
    kde-open "$@" >/dev/null 2>&1
}

function start() {
  local _ret=0
  for arg ; do
    start_one "$arg"
    _ret=$(( $_ret | $? ))
  done
  return $_ret
}

start "$@"
